import { Body, Controller, Delete, Get, Param, Patch, Post, Query } from '@nestjs/common'; import { ApiBearerAuth, ApiTags } from '@nestjs/swagger'; import { InjectRepository } from '@nestjs/typeorm'; import { DataSource, ILike, IsNull, Raw, Repository } from 'typeorm'; import { createHash,randomBytes } from 'crypto'; import * as argon2 from 'argon2';
import { CurrentUser, RequestContext } from '../common/request-context'; import { AcceptInvitationDto,InviteMemberDto, TeamQueryDto, UpdateMemberDto } from './team.dto'; import { pageOf } from '../common/api-response'; import { toOrder } from '../common/page-query.dto'; import { Roles, UserRole } from '../auth/authorization'; import { DomainError } from '../common/domain-error'; import { Public } from '../auth/public.decorator'; import { UserEntity } from '../auth/auth.entity';
import { OrganizationEntity } from '../onboarding/onboarding.entity';
import { TeamMemberEntity } from './team.entity';
import { TeamInvitationEntity } from './team.entity';
import { Throttle } from '@nestjs/throttler';
import { ReliabilityService } from '../operations/reliability.service';
import { invitationEmail } from '../operations/email-templates';
@ApiTags('team') @ApiBearerAuth() @Controller('team/members') export class TeamController {
  constructor(@InjectRepository(TeamMemberEntity) private readonly members: Repository<TeamMemberEntity>,@InjectRepository(TeamInvitationEntity)private readonly invitations:Repository<TeamInvitationEntity>,@InjectRepository(UserEntity)private readonly users:Repository<UserEntity>,private readonly db:DataSource,private readonly reliability:ReliabilityService) {}
  @Get() async list(@CurrentUser() user: RequestContext, @Query() query: TeamQueryDto) { const where = { organizationId: user.organizationId, ...(query.role ? { role: query.role } : {}), ...(query.status ? { status: query.status } : {}), ...(query.search ? { email: ILike(`%${query.search}%`) } : {}) }; const order = toOrder(query.sortBy, query.sortDirection, ['firstName', 'lastName', 'email', 'role', 'status', 'createdAt', 'updatedAt'] as const, 'createdAt'); const [data,total] = await this.members.findAndCount({ where, order, skip:(query.page-1)*query.pageSize, take:query.pageSize }); return pageOf(data,total,query.page,query.pageSize,query.sortBy,query.sortDirection); }
  @Roles(UserRole.Admin) @Post('invite') async invite(@CurrentUser() user: RequestContext, @Body() dto: InviteMemberDto) { const email=dto.email.trim().toLowerCase(),sameEmail=Raw(column=>`LOWER(TRIM(${column})) = :email`,{email});if(await this.users.existsBy({email:sameEmail}))throw new DomainError('This email already belongs to a registered user','TEAM_EMAIL_ALREADY_REGISTERED',409);if(await this.invitations.existsBy({email:sameEmail,revokedAt:IsNull(),acceptedAt:IsNull()}))throw new DomainError('An active invitation has already been sent to this email','TEAM_INVITATION_EXISTS',409);const token=randomBytes(32).toString('base64url');const invitation=await this.db.transaction(async m=>{const row=await m.save(TeamInvitationEntity,m.create(TeamInvitationEntity,{organizationId:user.organizationId,...dto,email,pendingEmail:email,tokenHash:createHash('sha256').update(token).digest('hex'),invitedBy:user.userId,expiresAt:new Date(Date.now()+7*86400000)}));const link=`${process.env.APP_PUBLIC_URL??'http://localhost:5173'}/first-time-register?token=${encodeURIComponent(token)}`;await this.reliability.enqueue(m,'email.send','invitation',row.id,{to:row.email,...invitationEmail({firstName:row.firstName,role:row.role,invitationUrl:link,expiresInDays:7})});return row});return {invitation:{id:invitation.id,email:invitation.email,role:invitation.role,expiresAt:invitation.expiresAt},...(process.env.NODE_ENV==='test'?{token}:{})}; }
  @Roles(UserRole.Admin) @Get('invitations') async listInvitations(@CurrentUser()u:RequestContext,@Query()q:TeamQueryDto){const order=toOrder(q.sortBy,q.sortDirection,['email','role','createdAt','expiresAt'] as const,'createdAt');const where={organizationId:u.organizationId,revokedAt:IsNull(),...(q.role?{role:q.role}:{}),...(q.search?{email:ILike(`%${q.search}%`)}:{})};const[data,total]=await this.invitations.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data.map(({tokenHash,...safe})=>safe),total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
  @Roles(UserRole.Admin) @Post('invitations/:id/resend')async resend(@CurrentUser()u:RequestContext,@Param('id')id:string){const token=randomBytes(32).toString('base64url');const row=await this.db.transaction(async m=>{const invitation=await m.findOneBy(TeamInvitationEntity,{id,organizationId:u.organizationId,revokedAt:IsNull(),acceptedAt:IsNull()});if(!invitation)throw new DomainError('Invitation was not found','INVITATION_NOT_FOUND',404);invitation.tokenHash=createHash('sha256').update(token).digest('hex');invitation.expiresAt=new Date(Date.now()+7*86400000);await m.save(TeamInvitationEntity,invitation);const link=`${process.env.APP_PUBLIC_URL??'http://localhost:5173'}/first-time-register?token=${encodeURIComponent(token)}`;await this.reliability.enqueue(m,'email.send','invitation',invitation.id,{to:invitation.email,...invitationEmail({firstName:invitation.firstName,role:invitation.role,invitationUrl:link,expiresInDays:7,resent:true})});return invitation});return{id:row.id,email:row.email,expiresAt:row.expiresAt,...(process.env.NODE_ENV==='test'?{token}:{})}}
  @Roles(UserRole.Admin) @Delete('invitations/:id') async revoke(@CurrentUser()u:RequestContext,@Param('id')id:string){const row=await this.invitations.findOneBy({id,organizationId:u.organizationId,revokedAt:IsNull()});if(!row)throw new DomainError('Invitation was not found','INVITATION_NOT_FOUND',404);row.revokedAt=new Date();row.pendingEmail=null;await this.invitations.save(row);return{revoked:true}}
  @Get(':id') async get(@CurrentUser() user: RequestContext, @Param('id') id: string) { const row = await this.members.findOneBy({ id, organizationId:user.organizationId }); if(!row) throw new DomainError('Team member was not found','MEMBER_NOT_FOUND',404); return row; }
  @Roles(UserRole.Admin) @Patch(':id') async update(@CurrentUser() user: RequestContext, @Param('id') id: string, @Body() dto: UpdateMemberDto) { return this.db.transaction(async m=>{const row=await m.findOneBy(TeamMemberEntity,{id,organizationId:user.organizationId});if(!row)throw new DomainError('Team member was not found','MEMBER_NOT_FOUND',404);if(row.role==='admin'&&dto.role!=='admin'&&row.status==='active'&&await m.countBy(UserEntity,{organizationId:user.organizationId,role:'admin',isActive:true})<=1)throw new DomainError('The final active administrator cannot be demoted','FINAL_ADMIN_REQUIRED',409);Object.assign(row,dto);if(row.userId)await m.update(UserEntity,{id:row.userId,organizationId:user.organizationId},{firstName:dto.firstName,lastName:dto.lastName,role:dto.role});return m.save(TeamMemberEntity,row)}); }
  @Roles(UserRole.Admin) @Delete(':id') async deactivate(@CurrentUser() user: RequestContext, @Param('id') id: string) { return this.db.transaction(async m=>{const row=await m.findOneBy(TeamMemberEntity,{id,organizationId:user.organizationId});if(!row)throw new DomainError('Team member was not found','MEMBER_NOT_FOUND',404);if(row.userId===user.userId)throw new DomainError('You cannot deactivate your own account','SELF_DEACTIVATION',409);if(row.role==='admin'&&row.status==='active'&&await m.countBy(UserEntity,{organizationId:user.organizationId,role:'admin',isActive:true})<=1)throw new DomainError('The final active administrator cannot be deactivated','FINAL_ADMIN_REQUIRED',409);row.status='inactive';if(row.userId)await m.update(UserEntity,{id:row.userId,organizationId:user.organizationId},{isActive:false});return m.save(TeamMemberEntity,row)}); }
  @Roles(UserRole.Admin) @Post(':id/reactivate') async reactivate(@CurrentUser() user: RequestContext, @Param('id') id:string) { return this.db.transaction(async m=>{const row=await m.findOneBy(TeamMemberEntity,{id,organizationId:user.organizationId});if(!row)throw new DomainError('Team member was not found','MEMBER_NOT_FOUND',404);row.status='active';if(row.userId)await m.update(UserEntity,{id:row.userId,organizationId:user.organizationId},{isActive:true});return m.save(TeamMemberEntity,row)}); }
}
@Public() @ApiTags('invitations') @Controller('invitations') export class PublicInvitationController{constructor(@InjectRepository(TeamInvitationEntity)private readonly invitations:Repository<TeamInvitationEntity>,private readonly db:DataSource){}
 @Throttle({default:{limit:20,ttl:60000}}) @Get(':token/summary')async summary(@Param('token')token:string){const row=await this.find(token);return{firstName:row.firstName,lastName:row.lastName,email:row.email,role:row.role,expiresAt:row.expiresAt}}
 @Throttle({default:{limit:5,ttl:60000}}) @Post('accept')async accept(@Body()dto:AcceptInvitationDto){const invitation=await this.find(dto.token);return this.db.transaction(async m=>{if(await m.existsBy(UserEntity,{email:invitation.email}))throw new DomainError('An account already exists','ACCOUNT_EXISTS',409);const org=await m.findOneBy(OrganizationEntity,{id:invitation.organizationId});const userRole=org?.companyName==='goVerifEye Platform Ops'?'platform_admin':invitation.role;const user=await m.save(UserEntity,m.create(UserEntity,{email:invitation.email,firstName:invitation.firstName,lastName:invitation.lastName,role:userRole,organizationId:invitation.organizationId,passwordHash:await argon2.hash(dto.password,{type:argon2.argon2id})}));await m.save(TeamMemberEntity,m.create(TeamMemberEntity,{organizationId:invitation.organizationId,userId:user.id,firstName:invitation.firstName,lastName:invitation.lastName,email:invitation.email,role:invitation.role,status:'active'}));invitation.acceptedAt=new Date();invitation.pendingEmail=null;await m.save(TeamInvitationEntity,invitation);return{id:user.id,email:user.email,accepted:true}})}
 private async find(token:string){const hash=createHash('sha256').update(token).digest('hex');const row=await this.invitations.findOneBy({tokenHash:hash,revokedAt:IsNull(),acceptedAt:IsNull()});if(!row||row.expiresAt.getTime()<Date.now())throw new DomainError('Invitation is invalid or expired','INVALID_INVITATION',404);return row}}
