import{Body,Controller,Get,Param,Post,Query}from'@nestjs/common';import{ApiBearerAuth,ApiTags}from'@nestjs/swagger';import{InjectRepository}from'@nestjs/typeorm';import{Repository}from'typeorm';import{CurrentUser,RequestContext}from'../common/request-context';import{DomainError}from'../common/domain-error';import{pageOf}from'../common/api-response';import{toOrder}from'../common/page-query.dto';import{ProductEntity}from'../products/product.entity';import{BackgroundJobEntity,PaymentEntity,SupportTicketEntity}from'./commerce.entity';import{CreateExportJobDto,CreatePaymentDto,CreateSupportTicketDto,JobQueryDto,QuoteDto}from'./commerce.dto';
@ApiBearerAuth()@ApiTags('commerce')@Controller()export class CommerceController{constructor(@InjectRepository(ProductEntity)private readonly products:Repository<ProductEntity>,@InjectRepository(PaymentEntity)private readonly payments:Repository<PaymentEntity>,@InjectRepository(BackgroundJobEntity)private readonly jobs:Repository<BackgroundJobEntity>,@InjectRepository(SupportTicketEntity)private readonly tickets:Repository<SupportTicketEntity>){}
 @Post('code-batch-quotes')async quote(@CurrentUser()u:RequestContext,@Body()d:QuoteDto){const p=await this.products.findOneBy({id:d.productId,organizationId:u.organizationId});if(!p)throw new DomainError('Product was not found','PRODUCT_NOT_FOUND',404);const unit=d.labelType==='pair'?14.25:7.5;return{productId:p.id,quantity:d.quantity,labelType:d.labelType,unitPrice:unit,subtotal:Number((unit*d.quantity).toFixed(2)),currency:'NGN',expiresAt:new Date(Date.now()+15*60000)}}
 @Post('payments')async payment(@CurrentUser()u:RequestContext,@Body()d:CreatePaymentDto){const q=await this.quote(u,d);return this.payments.save(this.payments.create({organizationId:u.organizationId,createdBy:u.userId,productId:d.productId,quantity:d.quantity,amount:String(q.subtotal),currency:q.currency,method:d.method,status:'pending'}))}
 @Get('payments/:id')async getPayment(@CurrentUser()u:RequestContext,@Param('id')id:string){const row=await this.payments.findOneBy({id,organizationId:u.organizationId});if(!row)throw new DomainError('Payment was not found','PAYMENT_NOT_FOUND',404);return row}
 @Get('payments')async listPayments(@CurrentUser()u:RequestContext,@Query()q:JobQueryDto){const where={organizationId:u.organizationId,...(q.status?{status:q.status}:{})};const order=toOrder(q.sortBy,q.sortDirection,['createdAt','updatedAt','status','amount']as const,'createdAt');const[data,total]=await this.payments.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 @Post('jobs')createJob(@CurrentUser()u:RequestContext,@Body()d:CreateExportJobDto){return this.jobs.save(this.jobs.create({organizationId:u.organizationId,createdBy:u.userId,type:d.type,payload:{batchId:d.batchId,format:d.format},status:'queued'}))}
 @Get('jobs')async listJobs(@CurrentUser()u:RequestContext,@Query()q:JobQueryDto){const where={organizationId:u.organizationId,...(q.type?{type:q.type}:{}),...(q.status?{status:q.status}:{})};const order=toOrder(q.sortBy,q.sortDirection,['createdAt','updatedAt','type','status']as const,'createdAt');const[data,total]=await this.jobs.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 @Get('jobs/:id')async job(@CurrentUser()u:RequestContext,@Param('id')id:string){const row=await this.jobs.findOneBy({id,organizationId:u.organizationId});if(!row)throw new DomainError('Job was not found','JOB_NOT_FOUND',404);return row}
 @Post('support-tickets')ticket(@CurrentUser()u:RequestContext,@Body()d:CreateSupportTicketDto){return this.tickets.save(this.tickets.create({...d,organizationId:u.organizationId,createdBy:u.userId}))}
 @Get('support-tickets')async listTickets(@CurrentUser()u:RequestContext,@Query()q:JobQueryDto){const where={organizationId:u.organizationId,...(q.status?{status:q.status}:{})};const order=toOrder(q.sortBy,q.sortDirection,['createdAt','updatedAt','status','subject']as const,'createdAt');const[data,total]=await this.tickets.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
}
