import { MigrationInterface,QueryRunner,Table,TableColumn,TableIndex } from 'typeorm';
const base=[{name:'id',type:'uuid',isPrimary:true,isGenerated:true,generationStrategy:'uuid' as const},{name:'createdAt',type:'timestamp',default:'CURRENT_TIMESTAMP'},{name:'updatedAt',type:'timestamp',default:'CURRENT_TIMESTAMP'},{name:'version',type:'int',default:1}];
export class CompletePortalSchema1722200000000 implements MigrationInterface{async up(q:QueryRunner){
 for(const col of [new TableColumn({name:'firstName',type:'varchar',default:"''"}),new TableColumn({name:'lastName',type:'varchar',default:"''"}),new TableColumn({name:'phone',type:'varchar',isNullable:true})])await q.addColumn('users',col);
 await q.createTable(new Table({name:'auth_sessions',columns:[...base,{name:'userId',type:'uuid'},{name:'organizationId',type:'uuid'},{name:'refreshTokenHash',type:'varchar'},{name:'expiresAt',type:'timestamp'},{name:'revokedAt',type:'timestamp',isNullable:true},{name:'rotation',type:'int',default:0}]}));
 await q.createIndex('auth_sessions',new TableIndex({name:'IDX_auth_sessions_user',columnNames:['userId','organizationId']}));
 await q.createTable(new Table({name:'organization_documents',columns:[...base,{name:'organizationId',type:'uuid'},{name:'type',type:'varchar'},{name:'fileName',type:'varchar'},{name:'mimeType',type:'varchar'},{name:'size',type:'int'},{name:'storageKey',type:'varchar'},{name:'status',type:'varchar',default:"'uploaded'"},{name:'uploadedBy',type:'uuid'}]}));
 await q.createIndex('organization_documents',new TableIndex({name:'IDX_org_documents_tenant_created',columnNames:['organizationId','createdAt']}));
 await q.createTable(new Table({name:'audit_logs',columns:[...base,{name:'organizationId',type:'uuid'},{name:'actorId',type:'uuid'},{name:'action',type:'varchar'},{name:'resourceType',type:'varchar'},{name:'resourceId',type:'varchar',isNullable:true},{name:'status',type:'varchar',default:"'success'"},{name:'correlationId',type:'varchar',isNullable:true},{name:'metadata',type:'json',isNullable:true}]}));
 await q.createIndex('audit_logs',new TableIndex({name:'IDX_audit_tenant_created',columnNames:['organizationId','createdAt']}));
 await q.createTable(new Table({name:'notifications',columns:[...base,{name:'organizationId',type:'uuid'},{name:'userId',type:'uuid'},{name:'type',type:'varchar'},{name:'title',type:'varchar'},{name:'message',type:'text'},{name:'isRead',type:'boolean',default:false},{name:'readAt',type:'timestamp',isNullable:true}]}));
 await q.createIndex('notifications',new TableIndex({name:'IDX_notifications_user_created',columnNames:['organizationId','userId','createdAt']}));
 await q.createTable(new Table({name:'verification_events',columns:[...base,{name:'organizationId',type:'uuid'},{name:'productId',type:'uuid'},{name:'codeId',type:'uuid'},{name:'outcome',type:'varchar',default:"'valid'"},{name:'location',type:'varchar',isNullable:true}]}));
 await q.createIndex('verification_events',new TableIndex({name:'IDX_verification_events_tenant_created',columnNames:['organizationId','createdAt']}));
 }async down(q:QueryRunner){for(const table of ['verification_events','notifications','audit_logs','organization_documents','auth_sessions'])await q.dropTable(table,true);for(const name of ['phone','lastName','firstName'])await q.dropColumn('users',name);}}
