import { Body,Controller,Delete,Get,Param,Patch,Post,Put,Query } from '@nestjs/common'; import { ApiBearerAuth,ApiTags } from '@nestjs/swagger'; import { InjectRepository } from '@nestjs/typeorm'; import { ILike,Repository } from 'typeorm'; import { randomUUID } from 'crypto'; import { pageOf } from '../common/api-response'; import { DomainError } from '../common/domain-error'; import { toOrder } from '../common/page-query.dto'; import { CurrentUser,RequestContext } from '../common/request-context';
import { CompleteOnboardingDto,CreateDocumentDto,DocumentQueryDto,UpdateAddressDto,UpdateAdministratorDto,UpdateCompanyOnboardingDto,UpdateDocumentDto } from './onboarding.dto'; import { OrganizationDocumentEntity,OrganizationEntity } from './onboarding.entity';
@ApiTags('onboarding') @ApiBearerAuth() @Controller('onboarding') export class OnboardingController {constructor(@InjectRepository(OrganizationEntity)private readonly organizations:Repository<OrganizationEntity>,@InjectRepository(OrganizationDocumentEntity)private readonly docs:Repository<OrganizationDocumentEntity>){}
 @Put() async complete(@CurrentUser()u:RequestContext,@Body()dto:CompleteOnboardingDto){const existing=await this.organizations.findOneBy({id:u.organizationId});return this.organizations.save(this.organizations.create({...existing,id:u.organizationId,...dto,status:'submitted'}))}
 @Get() async get(@CurrentUser()u:RequestContext){return await this.organizations.findOneBy({id:u.organizationId})??{status:'not_started'}}
 @Patch('company') async company(@CurrentUser()u:RequestContext,@Body()dto:UpdateCompanyOnboardingDto){const row=await this.organizations.findOneBy({id:u.organizationId});return this.organizations.save(this.organizations.create({...row,id:u.organizationId,...dto,status:'draft',administrator:row?.administrator??{},address:row?.address??{},documents:row?.documents??[]}))}
 @Patch('administrator') async administrator(@CurrentUser()u:RequestContext,@Body()dto:UpdateAdministratorDto){const row=await this.required(u.organizationId);row.administrator={...row.administrator,...dto};row.status='draft';return this.organizations.save(row)}
 @Patch('address') async address(@CurrentUser()u:RequestContext,@Body()dto:UpdateAddressDto){const row=await this.required(u.organizationId);row.address={...row.address,...dto};row.status='draft';return this.organizations.save(row)}
 @Post('submit') async submit(@CurrentUser()u:RequestContext){const row=await this.required(u.organizationId);const count=await this.docs.countBy({organizationId:u.organizationId});if(!row.companyName||!row.administrator?.email||!row.address?.country||count===0)throw new DomainError('Onboarding is incomplete','ONBOARDING_INCOMPLETE',409);row.status='submitted';return this.organizations.save(row)}
 @Get('documents') async documents(@CurrentUser()u:RequestContext,@Query()q:DocumentQueryDto){const where={organizationId:u.organizationId,...(q.type?{type:q.type}:{}),...(q.status?{status:q.status}:{}),...(q.search?{fileName:ILike(`%${q.search}%`)}:{})};const order=toOrder(q.sortBy,q.sortDirection,['fileName','type','status','createdAt','updatedAt'] as const,'createdAt');const[data,total]=await this.docs.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 @Post('documents') addDocument(@CurrentUser()u:RequestContext,@Body()dto:CreateDocumentDto){const safeName=dto.fileName.replace(/[^a-zA-Z0-9._-]/g,'_');return this.docs.save(this.docs.create({...dto,storageKey:`organizations/${u.organizationId}/documents/${randomUUID()}-${safeName}`,organizationId:u.organizationId,uploadedBy:u.userId}))}
 @Get('documents/:id') async document(@CurrentUser()u:RequestContext,@Param('id')id:string){const row=await this.docs.findOneBy({id,organizationId:u.organizationId});if(!row)throw new DomainError('Document was not found','DOCUMENT_NOT_FOUND',404);return row}
 @Patch('documents/:id') async updateDocument(@CurrentUser()u:RequestContext,@Param('id')id:string,@Body()dto:UpdateDocumentDto){const row=await this.document(u,id);const safeName=dto.fileName?.replace(/[^a-zA-Z0-9._-]/g,'_');return this.docs.save({...row,...dto,...(safeName?{storageKey:`organizations/${u.organizationId}/documents/${randomUUID()}-${safeName}`}:{})})}
 @Delete('documents/:id') async deleteDocument(@CurrentUser()u:RequestContext,@Param('id')id:string){const result=await this.docs.delete({id,organizationId:u.organizationId});if(!result.affected)throw new DomainError('Document was not found','DOCUMENT_NOT_FOUND',404);return{deleted:true}}
 private async required(id:string){const row=await this.organizations.findOneBy({id});if(!row)throw new DomainError('Onboarding has not started','ONBOARDING_NOT_FOUND',404);return row}
}
