import { Injectable, ServiceUnavailableException } from '@nestjs/common';
export interface EmailMessage { to:string; subject:string; text:string; html?:string }
@Injectable() export class GmailEmailService {
 private token?:{value:string;expiresAt:number};
 async send(message:EmailMessage):Promise<{id:string}>{this.assertConfigured();const access=await this.accessToken();const raw=Buffer.from(this.mime(message)).toString('base64url');const response=await fetch(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(process.env.GMAIL_USER_ID!)}/messages/send`,{method:'POST',headers:{authorization:`Bearer ${access}`,'content-type':'application/json'},body:JSON.stringify({raw}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new ServiceUnavailableException(`Gmail API rejected the message (${response.status})`);return response.json() as Promise<{id:string}>}
 private async accessToken(){if(this.token&&this.token.expiresAt>Date.now()+60000)return this.token.value;const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GMAIL_CLIENT_ID!,client_secret:process.env.GMAIL_CLIENT_SECRET!,refresh_token:process.env.GMAIL_REFRESH_TOKEN!,grant_type:'refresh_token'}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new ServiceUnavailableException(`Google OAuth token refresh failed (${response.status})`);const body=await response.json()as{access_token:string;expires_in:number};this.token={value:body.access_token,expiresAt:Date.now()+body.expires_in*1000};return body.access_token}
 private mime(m:EmailMessage){const clean=(v:string)=>v.replace(/[\r\n]/g,' ').trim(),boundary=`goverifeye_${Date.now().toString(36)}`;return[`From: ${clean(process.env.GMAIL_FROM_NAME??'goVerifEye')} <${clean(process.env.GMAIL_FROM_EMAIL!)}>`,`To: ${clean(m.to)}`,`Subject: ${clean(m.subject)}`,'MIME-Version: 1.0',`Content-Type: multipart/alternative; boundary="${boundary}"`,'',`--${boundary}`,'Content-Type: text/plain; charset="UTF-8"','',m.text,...(m.html?[`--${boundary}`,'Content-Type: text/html; charset="UTF-8"','',m.html]:[]),`--${boundary}--`,''].join('\r\n')}
 private assertConfigured(){const keys=['GMAIL_CLIENT_ID','GMAIL_CLIENT_SECRET','GMAIL_REFRESH_TOKEN','GMAIL_USER_ID','GMAIL_FROM_EMAIL'];if(keys.some(k=>!process.env[k]||process.env[k]!.startsWith('replace-')))throw new ServiceUnavailableException('Gmail API is not configured')}
}
