import { IsBoolean, IsIn, IsInt, IsOptional, IsString, IsUrl, Length, Max, Min } from 'class-validator'; import { PageQueryDto } from '../common/page-query.dto'; import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { AddressDto } from '../onboarding/onboarding.dto';
import { ValidateNested } from 'class-validator';
export class AuditQueryDto extends PageQueryDto { @IsOptional() @IsString() actorId?:string; @IsOptional() @IsString() action?:string; @IsOptional() @IsString() resourceType?:string; @IsOptional() @IsString() resourceId?:string; @IsOptional() @IsString() status?:string; @IsIn(['createdAt','action','resourceType','status']) override sortBy='createdAt'; }
export class NotificationQueryDto extends PageQueryDto { @IsOptional() @Type(()=>Boolean) @IsBoolean() read?:boolean; @IsOptional() @IsString() type?:string; @IsIn(['createdAt','type','title','isRead']) override sortBy='createdAt'; }
export class UpdateProfileDto { @ApiProperty({example:'Ada'}) @IsString() @Length(1,100) firstName!:string; @ApiProperty({example:'Okafor'}) @IsString() @Length(1,100) lastName!:string; @ApiPropertyOptional({example:'Compliance Manager'}) @IsOptional() @IsString() @Length(1,100) jobTitle?:string; @ApiPropertyOptional({example:'+2348012345678'}) @IsOptional() @IsString() phone?:string; @ApiPropertyOptional({format:'uri'}) @IsOptional() @IsUrl() profileImageUrl?:string; }
export class CreateProfileImageUploadDto { @ApiProperty({example:'profile.jpg'}) @IsString() @Length(1,200) fileName!:string; @ApiProperty({enum:['image/png','image/jpeg']}) @IsIn(['image/png','image/jpeg']) mimeType!:string; @ApiProperty({maximum:2097152}) @Type(()=>Number) @IsInt() @Min(1) @Max(2*1024*1024) size!:number; }
export class UpdateCompanyDto { @ApiProperty({example:'Verified Goods Ltd'}) @IsString() @Length(2,200) companyName!:string; @ApiProperty({example:'Pharmaceuticals'}) @IsString() industry!:string; @ApiProperty({example:'Nigeria'}) @IsString() country!:string; @ApiPropertyOptional({example:'https://example.com'}) @IsOptional() @IsString() @Length(1,500) website?:string; @ApiPropertyOptional({type:()=>AddressDto}) @IsOptional() @ValidateNested() @Type(()=>AddressDto) address?:AddressDto; }
export class ChangePasswordDto { @ApiProperty({example:'CurrentPass123!'}) @IsString() currentPassword!:string; @ApiProperty({example:'NewSecurePass123!',minLength:6,maxLength:128}) @IsString() @Length(6,128) newPassword!:string; }
