import { Injectable } from '@nestjs/common'; import { DataSource, ILike } from 'typeorm'; import * as argon2 from 'argon2';
import { pageOf } from '../common/api-response'; import { toOrder } from '../common/page-query.dto'; import { DomainError } from '../common/domain-error'; import { UserEntity } from '../auth/auth.entity'; import { OrganizationEntity } from '../onboarding/onboarding.entity';
import { AuditLogEntity, NotificationEntity } from './operations.entity'; import { AuditQueryDto, ChangePasswordDto, NotificationQueryDto, UpdateCompanyDto, UpdateProfileDto } from './operations.dto';
@Injectable() export class OperationsService {
  constructor(private readonly db:DataSource) {}
  async audit(organizationId:string, actorId:string, action:string, resourceType:string, resourceId?:string, metadata?:Record<string,unknown>) { return this.db.getRepository(AuditLogEntity).save({ organizationId,actorId,action,resourceType,resourceId,metadata,status:'success' }); }
  async listAudit(organizationId:string,q:AuditQueryDto){ const repo=this.db.getRepository(AuditLogEntity); const where={organizationId,...(q.actorId?{actorId:q.actorId}:{}),...(q.action?{action:q.action}:{}),...(q.resourceType?{resourceType:q.resourceType}:{}),...(q.resourceId?{resourceId:q.resourceId}:{}),...(q.status?{status:q.status}:{}),...(q.search?{action:ILike(`%${q.search}%`)}:{})}; const order=toOrder(q.sortBy,q.sortDirection,['createdAt','action','resourceType','status'] as const,'createdAt'); const [data,total]=await repo.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize}); return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection); }
  async listNotifications(organizationId:string,userId:string,q:NotificationQueryDto){ const repo=this.db.getRepository(NotificationEntity); const where={organizationId,userId,...(q.read!==undefined?{isRead:q.read}:{}),...(q.type?{type:q.type}:{}),...(q.search?{title:ILike(`%${q.search}%`)}:{})}; const order=toOrder(q.sortBy,q.sortDirection,['createdAt','type','title','isRead'] as const,'createdAt'); const [data,total]=await repo.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize}); return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection); }
  async markRead(organizationId:string,userId:string,id:string){ const repo=this.db.getRepository(NotificationEntity); const item=await repo.findOneBy({id,organizationId,userId}); if(!item) throw new DomainError('Notification was not found','NOTIFICATION_NOT_FOUND',404); item.isRead=true; item.readAt=new Date(); return repo.save(item); }
  async readAll(organizationId:string,userId:string){ await this.db.getRepository(NotificationEntity).update({organizationId,userId,isRead:false},{isRead:true,readAt:new Date()}); return {updated:true}; }
  async deleteNotification(organizationId:string,userId:string,id:string){ const result=await this.db.getRepository(NotificationEntity).delete({id,organizationId,userId}); if(!result.affected) throw new DomainError('Notification was not found','NOTIFICATION_NOT_FOUND',404); return {deleted:true}; }
  async profile(organizationId:string,userId:string){ const user=await this.db.getRepository(UserEntity).findOneBy({id:userId,organizationId}); if(!user) throw new DomainError('Profile was not found','PROFILE_NOT_FOUND',404); const {passwordHash,...safe}=user; return safe; }
  async updateProfile(organizationId:string,userId:string,dto:UpdateProfileDto){ const repo=this.db.getRepository(UserEntity); const user=await repo.findOneBy({id:userId,organizationId}); if(!user) throw new DomainError('Profile was not found','PROFILE_NOT_FOUND',404); Object.assign(user,dto); const saved=await repo.save(user); const {passwordHash,...safe}=saved; return safe; }
  async company(organizationId:string){ const row=await this.db.getRepository(OrganizationEntity).findOneBy({id:organizationId}); if(!row) throw new DomainError('Company was not found','COMPANY_NOT_FOUND',404); return row; }
  async updateCompany(organizationId:string,dto:UpdateCompanyDto){ const repo=this.db.getRepository(OrganizationEntity); const row=await repo.findOneBy({id:organizationId}); if(!row) throw new DomainError('Company was not found','COMPANY_NOT_FOUND',404); return repo.save({...row,...dto}); }
  async changePassword(organizationId:string,userId:string,dto:ChangePasswordDto){ const repo=this.db.getRepository(UserEntity); const user=await repo.findOneBy({id:userId,organizationId,isActive:true}); if(!user||!await argon2.verify(user.passwordHash,dto.currentPassword)) throw new DomainError('Current password is incorrect','INVALID_PASSWORD',401); user.passwordHash=await argon2.hash(dto.newPassword,{type:argon2.argon2id}); await repo.save(user); await this.audit(organizationId,userId,'password.changed','user',userId); return {changed:true}; }
  async deactivate(organizationId:string,userId:string){ return this.db.transaction(async manager=>{const repo=manager.getRepository(UserEntity);const user=await repo.findOneBy({id:userId,organizationId});if(!user)throw new DomainError('Profile was not found','PROFILE_NOT_FOUND',404);if(user.role==='admin'&&await repo.countBy({organizationId,role:'admin',isActive:true})<=1)throw new DomainError('The final active administrator cannot deactivate their account','FINAL_ADMIN_REQUIRED',409);user.isActive=false;await repo.save(user);await manager.getRepository(AuditLogEntity).save({organizationId,actorId:userId,action:'account.deactivated',resourceType:'user',resourceId:userId,status:'success'});await manager.getRepository(UserEntity);return{deactivated:true}}); }
}
