import { BeforeInsert, Column, Entity, Index, Unique } from 'typeorm'; import { randomUUID } from 'crypto'; import { BaseEntity } from '../database/base.entity'; import { BatchStatus, Fulfillment, LabelType, VerificationCodeStatus } from './code.enums';
export { BatchStatus, VerificationCodeStatus } from './code.enums';
@Entity('code_namespaces') export class CodeNamespaceEntity extends BaseEntity { @Column('uuid',{unique:true}) @Index() organizationId!:string; @Column({type:'char',length:4,unique:true}) @Index() namespace!:string; @Column({type:'bigint',default:'1'}) nextSerial!:string; }
@Entity('code_batches') @Index(['organizationId','clientRequestId'],{unique:true}) export class CodeBatchEntity extends BaseEntity { @Column('uuid') @Index() organizationId!: string; @Column({nullable:true}) clientRequestId?:string; @Column('uuid') @Index() productId!: string; @Column() labelType!: LabelType; @Column() fulfillment!: Fulfillment; @Column() quantity!: number; @Column({ nullable: true }) paperSize?: string; @Column({ nullable: true }) logisticsService?: string; @Column({type:'date',nullable:true}) manufacturingDate?:string; @Column({type:'date',nullable:true}) expiryDate?:string; @Column({default:'self_print_digital'}) activationMode!:'controlled_physical_print'|'self_print_digital'; @Column({nullable:true,select:false}) activationCredentialHash?:string|null; @Column({default:0}) activationAttempts!:number; @Column({type:'timestamp',nullable:true}) activatedAt?:Date|null; @Column('uuid',{nullable:true}) activatedBy?:string|null; @Column({ default: BatchStatus.Generating }) status!: BatchStatus; @Column({ default: 0 }) scanned!: number; @Column('uuid') generatedBy!: string; }
@Entity('verification_codes') @Unique('UQ_verification_codes_code', ['code']) @Index(['organizationId', 'productId'])
export class VerificationCodeEntity extends BaseEntity {
  @Column('uuid') @Index() organizationId!: string; @Column('uuid') @Index() productId!: string; @Column('uuid') @Index() batchId!: string;
  @Column({ type: 'varchar', length: 32 }) code!: string; @Column({type:'varchar',length:16,nullable:true}) codeFormatVersion?:string|null; @Column({type:'varchar',length:16,nullable:true}) keyVersion?:string|null;
  @Column({type:'char',length:4,nullable:true}) @Index() namespace?:string|null; @Column({type:'bigint',nullable:true}) internalSerial?:string|null; @Column({type:'char',length:7,nullable:true}) @Index() publicToken?:string|null; @Column({type:'char',length:1,nullable:true}) luhnDigit?:string|null; @Column({type:'char',length:4,nullable:true}) antiFabTag?:string|null; @Column('uuid',{nullable:true}) allocationId?:string|null; @Column('uuid',{nullable:true}) productBatchId?:string|null; @Column('uuid',{nullable:true}) unitId?:string|null; @Column({ type: 'varchar', length: 64, nullable:true, select:false }) activationCodeHash?: string|null;
  @Column({ type: 'varchar', length: 20, default: VerificationCodeStatus.Allocated }) status!: VerificationCodeStatus;
  @Column({ default: 0 }) activationAttempts!: number; @Column({ default: 0 }) verificationCount!: number; @Column({ type: 'timestamp', nullable: true }) activatedAt?: Date;
  @Column('uuid', { nullable: true }) activatedBy?: string; @Column({ type: 'timestamp', nullable: true }) lastVerifiedAt?: Date;
  @BeforeInsert() bindGve16Unit(){if(this.codeFormatVersion){this.id||=randomUUID();this.productBatchId??=this.batchId;this.unitId??=this.id;}}
}
@Entity('open_market_batches') export class OpenMarketBatchEntity extends BaseEntity { @Column({unique:true}) @Index() publicBatchId!:string; @Column() activationCodeHash!:string; @Column() labelType!:LabelType; @Column() quantity!:number; @Column({type:'decimal',precision:12,scale:2}) totalCost!:number; @Column({default:'available'}) status!:'available'|'claimed'; @Column('uuid',{nullable:true}) claimedByOrganizationId?:string; @Column('uuid',{nullable:true}) claimedCodeBatchId?:string; @Column({type:'timestamp',nullable:true}) claimedAt?:Date; }
@Entity('open_market_claims') @Index(['userId','inventoryBatchId']) export class OpenMarketClaimEntity extends BaseEntity { @Column('uuid') userId!:string; @Column('uuid') organizationId!:string; @Column('uuid') inventoryBatchId!:string; @Column('uuid',{nullable:true}) productId?:string; @Column({nullable:true}) otpHash?:string; @Column({type:'timestamp'}) expiresAt!:Date; @Column({default:0}) attempts!:number; @Column({default:false}) consumed!:boolean; }
@Entity('verification_events') @Index(['organizationId','createdAt']) export class VerificationEventEntity extends BaseEntity { @Column('uuid',{nullable:true}) organizationId!:string; @Column('uuid',{nullable:true}) productId!:string; @Column('uuid',{nullable:true}) codeId!:string; @Column({default:'valid'}) outcome!:string; @Column({default:'manual'}) channel!:string; @Column({nullable:true}) submittedCodeHash?:string|null; @Column({nullable:true}) location?:string; @Column({nullable:true}) ipAddress?:string; @Column({nullable:true}) customerComplaint?:string; @Column({nullable:true}) ipHash?:string; @Column({nullable:true}) userAgentHash?:string; @Column({nullable:true}) @Index() scannerHash?:string; @Column({default:0}) riskScore!:number; @Column({type:'json',nullable:true}) riskReasons?:string[]; }
@Entity('scan_sessions') export class ScanSessionEntity extends BaseEntity { @Column({unique:true}) scannerHash!:string; @Column() nonceHash!:string; @Column({type:'timestamptz'}) nonceExpiresAt!:Date; @Column({type:'timestamptz'}) expiresAt!:Date; @Column({type:'timestamptz'}) lastSeenAt!:Date; @Column({nullable:true}) ipHash?:string; @Column({nullable:true}) userAgentHash?:string; }
