import { Type } from 'class-transformer'; import { IsDateString, IsEnum, IsIn, IsInt, IsOptional, IsString, IsUUID, Length, Matches, Max, MaxLength, Min, ValidateIf } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { PageQueryDto } from '../common/page-query.dto'; import { BatchStatus, Fulfillment, LabelType, VerificationCodeStatus } from './code.enums';
export { BatchStatus, Fulfillment, LabelType, VerificationCodeStatus } from './code.enums';
export const LOGISTICS_SERVICES = ['GIG Logistics','DHL Express','ABC Courier Services','Pickup — Port Harcourt warehouse'] as const;
export class GenerateBatchDto { @ApiProperty({format:'uuid',example:'55af73e4-4c52-4c2a-aec5-030f218760a8'}) @IsUUID() productId!: string; @ApiProperty({enum:LabelType}) @IsEnum(LabelType) labelType!: LabelType; @ApiProperty({enum:Fulfillment}) @IsEnum(Fulfillment) fulfillment!: Fulfillment; @ApiProperty({minimum:100,maximum:10000,example:100}) @Type(() => Number) @IsInt() @Min(100) @Max(10000) quantity!: number; @ApiProperty({enum:['Letter','A4','A5','Roll'],example:'A4'}) @IsIn(['Letter','A4','A5','Roll']) paperSize!: string; @ApiPropertyOptional({enum:LOGISTICS_SERVICES,description:'Required when fulfillment is preprinted.'}) @ValidateIf((input:GenerateBatchDto)=>input.fulfillment===Fulfillment.Preprinted) @IsIn(LOGISTICS_SERVICES) logisticsService?: string; @ApiPropertyOptional({format:'date',example:'2026-07-27'}) @IsOptional() @IsDateString() manufacturingDate?:string; @ApiPropertyOptional({format:'date',example:'2028-07-27'}) @IsOptional() @IsDateString() expiryDate?:string; }
export class ActivateCodeDto { @ApiProperty({example:'1234567890123456',pattern:'^\\d{6,28}$',description:'Numeric verification code. The active length is managed by a platform administrator.'}) @Matches(/^\d{6,28}$/) verificationCode!: string; @ApiProperty({example:'123456',pattern:'^\\d{6,12}$'}) @Matches(/^\d{6,12}$/) activationCode!: string; }
export class VerifyProductCodeDto { @ApiProperty({example:'1234567890123456',pattern:'^\\d{6,28}$',description:'Numeric verification code. The active length is managed by a platform administrator.'}) @Matches(/^\d{6,28}$/) verificationCode!: string; @ApiPropertyOptional({example:'Lagos, Nigeria'}) @IsOptional() @IsString() @Length(2,100) location?:string; @ApiPropertyOptional({example:'The seal appeared damaged on arrival',maxLength:500}) @IsOptional() @IsString() @MaxLength(500) customerComplaint?:string; }
export class BatchQueryDto extends PageQueryDto { @IsOptional() @IsUUID() productId?: string; @IsOptional() @IsEnum(LabelType) labelType?: LabelType; @IsOptional() @IsEnum(Fulfillment) fulfillment?: Fulfillment; @IsOptional() @IsEnum(BatchStatus) status?: BatchStatus; @IsIn(['createdAt','quantity','status','labelType']) override sortBy='createdAt'; }
export class CodeQueryDto extends PageQueryDto { @IsOptional() @IsEnum(VerificationCodeStatus) status?: VerificationCodeStatus; @IsOptional() @Type(() => Number) @IsInt() @Min(0) verificationCountMin?: number; @IsIn(['code','status','createdAt','activatedAt','verificationCount','lastVerifiedAt']) override sortBy='createdAt'; }
export class OpenMarketLookupDto { @ApiProperty({example:'8567-5654-8645-9875'}) @IsString() @Length(8,40) batchId!:string; @ApiProperty({example:'654321'}) @IsString() @Length(6,32) activationCode!:string; }
export class OpenMarketLinkDto { @ApiProperty({format:'uuid'}) @IsUUID() productId!:string; }
export class OpenMarketVerifyDto { @ApiProperty({example:'123456'}) @Matches(/^\d{6}$/) code!:string; }
