import { Injectable } from '@nestjs/common'; import { Between,DataSource,In,LessThanOrEqual,MoreThan,MoreThanOrEqual } from 'typeorm'; import { pageOf } from '../common/api-response'; import { aggregateGeographicalActivity } from '../common/report-region'; import { ProductEntity } from '../products/product.entity'; import { BatchStatus, CodeBatchEntity, VerificationCodeEntity, VerificationCodeStatus, VerificationEventEntity } from '../codes/code.entity'; import { ReportingQueryDto } from './reporting.dto'; import { toOrder } from '../common/page-query.dto'; import { AuditLogEntity } from '../operations/operations.entity'; import { FraudCaseEntity } from '../governance/governance.entity'; import { CustomerCheckEntity, CustomerConcernEntity } from '../customer/customer.entity'; import { ProductStatus } from '../products/product.model';
@Injectable() export class ReportingService { constructor(private readonly db:DataSource){}
 async summary(organizationId:string,q:Partial<ReportingQueryDto>={}){const products=this.db.getRepository(ProductEntity),codes=this.db.getRepository(VerificationCodeEntity),events=this.db.getRepository(VerificationEventEntity),batches=this.db.getRepository(CodeBatchEntity),date=this.dateWhere(q),eventWhere={organizationId,...date};const activityQb=events.createQueryBuilder('e').select('COUNT(DISTINCT e.productId)','count').addSelect('COUNT(DISTINCT e.codeId)','distinctCodes').where('e.organizationId = :organizationId',{organizationId});if(q.from)activityQb.andWhere('e.createdAt >= :from',{from:new Date(q.from)});if(q.to)activityQb.andWhere('e.createdAt <= :to',{to:new Date(q.to)});const [totalProducts,totalCodes,scans,suspiciousScans,totalBatches,activity]=await Promise.all([products.countBy({organizationId}),codes.countBy({organizationId}),events.countBy(eventWhere),events.countBy({...eventWhere,outcome:'suspicious'}),batches.countBy({organizationId}),activityQb.getRawOne<{count:string;distinctCodes:string}>()]);return {range:q.range??'weekly',metrics:{totalProducts,productsWithActivity:Number(activity?.count??0),totalCodes,scans,distinctCodes:Number(activity?.distinctCodes??0),uniqueCodes:Number(activity?.distinctCodes??0),suspiciousScans,qualifiedScans:Math.max(0,scans-suspiciousScans),totalBatches}}}
 async report(organizationId:string,q:Partial<ReportingQueryDto>={}){const summary=await this.summary(organizationId,q);const statusRows=await this.db.getRepository(VerificationCodeEntity).createQueryBuilder('c').select('c.status','status').addSelect('COUNT(*)','count').where('c.organizationId = :organizationId',{organizationId}).groupBy('c.status').getRawMany<{status:string;count:string}>();return {...summary,verification:Object.fromEntries(statusRows.map(x=>[x.status,Number(x.count)]))}}
 async topProducts(organizationId:string,q:ReportingQueryDto){const repo=this.db.getRepository(ProductEntity);const order=toOrder(q.sortBy,q.sortDirection,['name','scanned','suspicious','totalCodes','updatedAt'] as const,'scanned');const [data,total]=await repo.findAndCount({where:{organizationId,scanned:MoreThan(0)},order,skip:(q.page-1)*q.pageSize,take:q.pageSize});const ids=data.map(p=>p.id),distinct=ids.length?await this.db.getRepository(VerificationEventEntity).createQueryBuilder('e').select('e.productId','productId').addSelect('COUNT(DISTINCT e.codeId)','count').where('e.organizationId = :organizationId',{organizationId}).andWhere('e.productId IN (:...ids)',{ids}).andWhere(q.from?'e.createdAt >= :from':'1=1',q.from?{from:new Date(q.from)}:{}).andWhere(q.to?'e.createdAt <= :to':'1=1',q.to?{to:new Date(q.to)}:{}).groupBy('e.productId').getRawMany<{productId:string;count:string}>():[];const counts=new Map(distinct.map(row=>[row.productId,Number(row.count)]));return pageOf(data.map(p=>({id:p.id,name:p.name,imageUrl:p.imageUrl,scans:p.scanned,distinctCodes:counts.get(p.id)??0,uniqueCodes:counts.get(p.id)??0,suspicious:p.suspicious,qualified:Math.max(0,p.scanned-p.suspicious),totalCodes:p.totalCodes})),total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 async needsAttention(organizationId:string){const batches=await this.db.getRepository(CodeBatchEntity).find({where:{organizationId,status:In([BatchStatus.Generated,BatchStatus.Allocated,BatchStatus.ReleasedForActivation])},order:{createdAt:'DESC'},take:5});const products=await this.db.getRepository(ProductEntity).find({where:{organizationId,status:ProductStatus.InformationRequired},order:{updatedAt:'DESC'},take:5});const anomalyCount=await this.db.getRepository(FraudCaseEntity).count({where:{organizationId,status:In(['open','investigating'])}});const concernRow=await this.db.getRepository(CustomerConcernEntity).createQueryBuilder('concern').innerJoin(CustomerCheckEntity,'check','check.id = concern.checkId').innerJoin(VerificationCodeEntity,'code','code.code = check.code AND code.organizationId = :organizationId',{organizationId}).where("concern.status IN ('new','reviewing')").select('COUNT(DISTINCT concern.id)','count').getRawOne<{count:string}>();return{data:[...batches.map(batch=>({id:`activate-${batch.id}`,kind:'activate_batch',title:'Activate batch',detail:`${batch.quantity.toLocaleString('en-US')} codes awaiting activation`,href:`/dashboard/manage-codes/${batch.id}`,count:1})),...products.map(product=>({id:`product-info-${product.id}`,kind:'product_info',title:'Information requested',detail:`${product.name}: ${product.informationRequest??'Additional product information is required'}`,href:'/dashboard/products',count:1})),...(anomalyCount?[{id:'anomaly-cases',kind:'anomaly',title:'Anomaly cases',detail:`${anomalyCount} open case${anomalyCount===1?'':'s'} need review`,href:'/dashboard/operations',count:anomalyCount}]:[]),...(Number(concernRow?.count??0)?[{id:'consumer-concerns',kind:'consumer_concern',title:'Consumer concerns',detail:`${Number(concernRow?.count)} report${Number(concernRow?.count)===1?'':'s'} need review`,href:'/dashboard/operations',count:Number(concernRow?.count)}]:[])]}}
 async suspicious(organizationId:string,q:ReportingQueryDto){const repo=this.db.getRepository(VerificationEventEntity);const order=toOrder(q.sortBy,q.sortDirection,['createdAt','outcome','location'] as const,'createdAt');const where={organizationId,outcome:'suspicious',...(q.productId?{productId:q.productId}:{}),...this.dateWhere(q)};const [data,total]=await repo.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize}),ids=[...new Set(data.map(row=>row.productId))],products=ids.length?await this.db.getRepository(ProductEntity).find({where:{organizationId,id:In(ids)},select:{id:true,name:true}}):[],names=new Map(products.map(product=>[product.id,product.name]));return pageOf(data.map(row=>({...row,productName:names.get(row.productId)??'Unknown product'})),total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 async events(organizationId:string,q:ReportingQueryDto){const repo=this.db.getRepository(VerificationEventEntity);const order=toOrder(q.sortBy,q.sortDirection,['createdAt','outcome','location'] as const,'createdAt');const where={organizationId,...(q.productId?{productId:q.productId}:{}),...this.dateWhere(q)};const[data,total]=await repo.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 async locations(organizationId:string,q:ReportingQueryDto){
  const apply=(qb:ReturnType<DataSource['createQueryBuilder']>)=>{
    qb.where('e.organizationId = :organizationId',{organizationId});
    if(q.productId)qb.andWhere('e.productId = :productId',{productId:q.productId});
    if(q.from)qb.andWhere('e.createdAt >= :from',{from:new Date(q.from)});
    if(q.to)qb.andWhere('e.createdAt <= :to',{to:new Date(q.to)});
    return qb;
  };
  // Sheet2 #55 — pull raw location buckets, then collapse to agreed regions.
  const raw=await apply(this.db.getRepository(VerificationEventEntity).createQueryBuilder('e'))
    .select(`COALESCE(NULLIF(e.location, ''), 'Unknown')`,'location')
    .addSelect('COUNT(*)','scans')
    .addSelect(`SUM(CASE WHEN e.outcome = 'suspicious' THEN 1 ELSE 0 END)`,'suspicious')
    .groupBy(`COALESCE(NULLIF(e.location, ''), 'Unknown')`)
    .orderBy('scans','DESC')
    .getRawMany<{location:string;scans:string;suspicious:string}>();
  const aggregated=aggregateGeographicalActivity(
    raw.map(row=>({location:row.location,scans:Number(row.scans),suspicious:Number(row.suspicious)})),
    {limit: 0},
  );
  const sorted=q.sortDirection==='asc'
    ? [...aggregated].sort((a,b)=>a.scans-b.scans)
    : aggregated;
  const total=sorted.length;
  const pageRows=sorted.slice((q.page-1)*q.pageSize,q.page*q.pageSize).map(row=>({
    location:row.state,
    scans:row.scans,
    suspicious:row.suspicious,
    percent:row.percent,
    scope:row.scope,
  }));
  return pageOf(pageRows,total,q.page,q.pageSize,'scans',q.sortDirection);
 }
 async trends(organizationId:string,q:ReportingQueryDto){const where={organizationId,...(q.productId?{productId:q.productId}:{}),...this.dateWhere(q)},rows=await this.db.getRepository(VerificationEventEntity).find({select:{createdAt:true,outcome:true},where,order:{createdAt:'ASC'}}),bucket=q.range==='monthly'?'month':q.range==='daily'?'day':'week',map=new Map<string,{period:string;scans:number;suspicious:number}>();for(const row of rows){const d=new Date(row.createdAt);if(bucket==='month'){d.setUTCDate(1);d.setUTCHours(0,0,0,0)}else if(bucket==='week'){d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));d.setUTCHours(0,0,0,0)}else d.setUTCHours(0,0,0,0);const key=d.toISOString(),item=map.get(key)??{period:key,scans:0,suspicious:0};item.scans++;if(row.outcome==='suspicious')item.suspicious++;map.set(key,item)}return{bucket,data:[...map.values()]}}
 async funnel(organizationId:string,q:ReportingQueryDto){const batchRepo=this.db.getRepository(CodeBatchEntity),codeRepo=this.db.getRepository(VerificationCodeEntity),eventRepo=this.db.getRepository(VerificationEventEntity),productFilter=q.productId?{productId:q.productId}:{};const[generated,active,awaiting,scanned,valid,suspicious]=await Promise.all([batchRepo.sum('quantity',{organizationId,...productFilter}),codeRepo.countBy({organizationId,status:VerificationCodeStatus.Active,...productFilter}),codeRepo.countBy({organizationId,status:VerificationCodeStatus.Inactive,...productFilter}),codeRepo.countBy({organizationId,lastVerifiedAt:MoreThanOrEqual(q.from?new Date(q.from):new Date(0)),...productFilter}),eventRepo.countBy({organizationId,outcome:'valid',...this.dateWhere(q),...productFilter}),eventRepo.countBy({organizationId,outcome:'suspicious',...this.dateWhere(q),...productFilter})]);return{generated:generated??0,awaitingActivation:awaiting,marketActive:active,active,scanned,valid,suspicious}}
 async productActivity(organizationId:string,productId:string,q:ReportingQueryDto){const repo=this.db.getRepository(AuditLogEntity);const order=toOrder(q.sortBy,q.sortDirection,['createdAt','action','status']as const,'createdAt');const[data,total]=await repo.findAndCount({where:{organizationId,resourceId:productId,...this.dateWhere(q)},order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 private dateWhere(q:Partial<ReportingQueryDto>){if(q.from&&q.to)return{createdAt:Between(new Date(q.from),new Date(q.to))};if(q.from)return{createdAt:MoreThanOrEqual(new Date(q.from))};if(q.to)return{createdAt:LessThanOrEqual(new Date(q.to))};return{}}
}
