import { Injectable } from '@nestjs/common'; import { Between,DataSource,LessThanOrEqual,MoreThanOrEqual } from 'typeorm'; import { pageOf } from '../common/api-response'; import { ProductEntity } from '../products/product.entity'; import { CodeBatchEntity, VerificationCodeEntity, VerificationCodeStatus, VerificationEventEntity } from '../codes/code.entity'; import { ReportingQueryDto } from './reporting.dto'; import { toOrder } from '../common/page-query.dto'; import { AuditLogEntity } from '../operations/operations.entity';
@Injectable() export class ReportingService { constructor(private readonly db:DataSource){}
 async summary(organizationId:string,range:string){const products=this.db.getRepository(ProductEntity),codes=this.db.getRepository(VerificationCodeEntity),events=this.db.getRepository(VerificationEventEntity),batches=this.db.getRepository(CodeBatchEntity);const [totalProducts,totalCodes,scans,suspiciousScans,totalBatches]=await Promise.all([products.countBy({organizationId}),codes.countBy({organizationId}),events.countBy({organizationId}),events.countBy({organizationId,outcome:'suspicious'}),batches.countBy({organizationId})]);return {range,metrics:{totalProducts,totalCodes,scans,suspiciousScans,totalBatches}}}
 async report(organizationId:string,range:string){const summary=await this.summary(organizationId,range);const statusRows=await this.db.getRepository(VerificationCodeEntity).createQueryBuilder('c').select('c.status','status').addSelect('COUNT(*)','count').where('c.organizationId = :organizationId',{organizationId}).groupBy('c.status').getRawMany<{status:string;count:string}>();return {...summary,verification:Object.fromEntries(statusRows.map(x=>[x.status,Number(x.count)]))}}
 async topProducts(organizationId:string,q:ReportingQueryDto){const repo=this.db.getRepository(ProductEntity);const order=toOrder(q.sortBy,q.sortDirection,['name','scanned','suspicious','totalCodes','updatedAt'] as const,'scanned');const [data,total]=await repo.findAndCount({where:{organizationId},order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data.map(p=>({id:p.id,name:p.name,scans:p.scanned,suspicious:p.suspicious,totalCodes:p.totalCodes})),total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 async suspicious(organizationId:string,q:ReportingQueryDto){const repo=this.db.getRepository(VerificationEventEntity);const order=toOrder(q.sortBy,q.sortDirection,['createdAt','outcome','location'] as const,'createdAt');const where={organizationId,outcome:'suspicious',...(q.productId?{productId:q.productId}:{}),...this.dateWhere(q)};const [data,total]=await repo.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 async events(organizationId:string,q:ReportingQueryDto){const repo=this.db.getRepository(VerificationEventEntity);const order=toOrder(q.sortBy,q.sortDirection,['createdAt','outcome','location'] as const,'createdAt');const where={organizationId,...(q.productId?{productId:q.productId}:{}),...this.dateWhere(q)};const[data,total]=await repo.findAndCount({where,order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 async locations(organizationId:string,q:ReportingQueryDto){const apply=(qb:ReturnType<DataSource['createQueryBuilder']>)=>{qb.where('e.organizationId = :organizationId',{organizationId}).andWhere('e.location IS NOT NULL');if(q.productId)qb.andWhere('e.productId = :productId',{productId:q.productId});if(q.from)qb.andWhere('e.createdAt >= :from',{from:new Date(q.from)});if(q.to)qb.andWhere('e.createdAt <= :to',{to:new Date(q.to)});return qb};const rows=await apply(this.db.getRepository(VerificationEventEntity).createQueryBuilder('e')).select('e.location','location').addSelect('COUNT(*)','scans').groupBy('e.location').orderBy('scans',q.sortDirection==='asc'?'ASC':'DESC').offset((q.page-1)*q.pageSize).limit(q.pageSize).getRawMany();const total=await apply(this.db.getRepository(VerificationEventEntity).createQueryBuilder('e')).select('COUNT(DISTINCT e.location)','count').getRawOne<{count:string}>();return pageOf(rows,Number(total?.count??0),q.page,q.pageSize,'scans',q.sortDirection)}
 async trends(organizationId:string,q:ReportingQueryDto){const where={organizationId,...(q.productId?{productId:q.productId}:{}),...this.dateWhere(q)},rows=await this.db.getRepository(VerificationEventEntity).find({select:{createdAt:true,outcome:true},where,order:{createdAt:'ASC'}}),bucket=q.range==='monthly'?'month':q.range==='daily'?'day':'week',map=new Map<string,{period:string;scans:number;suspicious:number}>();for(const row of rows){const d=new Date(row.createdAt);if(bucket==='month'){d.setUTCDate(1);d.setUTCHours(0,0,0,0)}else if(bucket==='week'){d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));d.setUTCHours(0,0,0,0)}else d.setUTCHours(0,0,0,0);const key=d.toISOString(),item=map.get(key)??{period:key,scans:0,suspicious:0};item.scans++;if(row.outcome==='suspicious')item.suspicious++;map.set(key,item)}return{bucket,data:[...map.values()]}}
 async funnel(organizationId:string,q:ReportingQueryDto){const batchRepo=this.db.getRepository(CodeBatchEntity),codeRepo=this.db.getRepository(VerificationCodeEntity),eventRepo=this.db.getRepository(VerificationEventEntity);const[generated,active,scanned,valid,suspicious]=await Promise.all([batchRepo.sum('quantity',{organizationId,...(q.productId?{productId:q.productId}:{})}),codeRepo.countBy({organizationId,status:VerificationCodeStatus.Active,...(q.productId?{productId:q.productId}:{})}),codeRepo.countBy({organizationId,lastVerifiedAt:MoreThanOrEqual(q.from?new Date(q.from):new Date(0)),...(q.productId?{productId:q.productId}:{})}),eventRepo.countBy({organizationId,outcome:'valid',...this.dateWhere(q),...(q.productId?{productId:q.productId}:{})}),eventRepo.countBy({organizationId,outcome:'suspicious',...this.dateWhere(q),...(q.productId?{productId:q.productId}:{})})]);return{generated:generated??0,active,scanned,valid,suspicious}}
 async productActivity(organizationId:string,productId:string,q:ReportingQueryDto){const repo=this.db.getRepository(AuditLogEntity);const order=toOrder(q.sortBy,q.sortDirection,['createdAt','action','status']as const,'createdAt');const[data,total]=await repo.findAndCount({where:{organizationId,resourceId:productId,...this.dateWhere(q)},order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(data,total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 private dateWhere(q:ReportingQueryDto){if(q.from&&q.to)return{createdAt:Between(new Date(q.from),new Date(q.to))};if(q.from)return{createdAt:MoreThanOrEqual(new Date(q.from))};if(q.to)return{createdAt:LessThanOrEqual(new Date(q.to))};return{}}
}
