import { ConflictException, Inject, Injectable, UnauthorizedException } from '@nestjs/common'; import { ConfigType } from '@nestjs/config'; import { JwtService } from '@nestjs/jwt'; import { InjectRepository } from '@nestjs/typeorm'; import * as argon2 from 'argon2'; import { createHash, randomInt, randomUUID } from 'crypto'; import { IsNull, Repository } from 'typeorm';
import appConfig from '../config/app.config'; import { AuthSessionEntity, OtpEntity, UserEntity } from './auth.entity'; import { SessionQueryDto } from './dto/auth.dto'; import { pageOf } from '../common/api-response'; import { toOrder } from '../common/page-query.dto'; import { DomainError } from '../common/domain-error';
interface RegistrationClaims {sub:string;email:string;purpose:'registration';challengeId:string}
interface RefreshClaims {sub:string;organizationId:string;role:string;sessionId:string;rotation:number;purpose:'refresh'}
@Injectable() export class AuthService {
 constructor(@Inject(appConfig.KEY)private readonly options:ConfigType<typeof appConfig>,private readonly jwt:JwtService,@InjectRepository(UserEntity)private readonly users:Repository<UserEntity>,@InjectRepository(OtpEntity)private readonly otps:Repository<OtpEntity>,@InjectRepository(AuthSessionEntity)private readonly sessions:Repository<AuthSessionEntity>){}
 async requestOtp(email:string){const normalized=email.trim().toLowerCase();const code=randomInt(0,1_000_000).toString().padStart(6,'0');const row=await this.otps.save(this.otps.create({email:normalized,hash:await argon2.hash(code,{type:argon2.argon2id}),expiresAt:new Date(Date.now()+this.options.otp.ttlSeconds*1000)}));return {challengeId:row.id,expiresInSeconds:this.options.otp.ttlSeconds,...(process.env.NODE_ENV==='test'?{code}:{})};}
 async verifyOtp(email:string,code:string){const key=email.trim().toLowerCase();const record=await this.otps.findOne({where:{email:key,consumed:false},order:{createdAt:'DESC'}});if(!record||record.expiresAt.getTime()<Date.now()||record.attempts>=this.options.otp.maxAttempts)throw new UnauthorizedException('Invalid or expired OTP');record.attempts+=1;if(!await argon2.verify(record.hash,code)){await this.otps.save(record);throw new UnauthorizedException('Invalid or expired OTP');}record.consumed=true;await this.otps.save(record);const registrationToken=this.jwt.sign({sub:key,email:key,purpose:'registration',challengeId:record.id},{secret:process.env.JWT_ACCESS_SECRET,expiresIn:'10m',issuer:'goverifeye-api',audience:'goverifeye-registration'});return {verified:true,registrationToken,expiresInSeconds:600};}
 async register(registrationToken:string,password:string){let claims:RegistrationClaims;try{claims=await this.jwt.verifyAsync<RegistrationClaims>(registrationToken,{secret:process.env.JWT_ACCESS_SECRET,issuer:'goverifeye-api',audience:'goverifeye-registration'});}catch{throw new UnauthorizedException('Invalid or expired registration proof');}if(claims.purpose!=='registration')throw new UnauthorizedException('Invalid registration proof');if(await this.users.existsBy({email:claims.email}))throw new ConflictException('An account already exists for this email');const organizationId=randomUUID();const user=await this.users.save(this.users.create({email:claims.email,organizationId,passwordHash:await argon2.hash(password,{type:argon2.argon2id}),role:'admin'}));return this.issueTokens(user);}
 async login(email:string,password:string){const user=await this.users.findOneBy({email:email.trim().toLowerCase(),isActive:true});if(!user||!await argon2.verify(user.passwordHash,password))throw new UnauthorizedException('Invalid credentials');return this.issueTokens(user);}
 async refresh(token:string){let claims:RefreshClaims;try{claims=await this.jwt.verifyAsync<RefreshClaims>(token,{secret:process.env.JWT_REFRESH_SECRET,issuer:'goverifeye-api',audience:'goverifeye-refresh'});}catch{throw new UnauthorizedException('Invalid refresh token');}const session=await this.sessions.findOneBy({id:claims.sessionId,userId:claims.sub,revokedAt:IsNull()});if(!session||session.expiresAt.getTime()<Date.now()||session.rotation!==claims.rotation||session.refreshTokenHash!==this.hash(token)){if(session){session.revokedAt=new Date();await this.sessions.save(session);}throw new UnauthorizedException('Refresh token replay or expiry detected');}const user=await this.users.findOneBy({id:claims.sub,organizationId:claims.organizationId,isActive:true});if(!user)throw new UnauthorizedException('Account is unavailable');session.rotation+=1;return this.issueTokens(user,session);}
 async logout(userId:string,organizationId:string,sessionId:string){await this.sessions.update({id:sessionId,userId,organizationId,revokedAt:IsNull()},{revokedAt:new Date()});return {loggedOut:true};}
 async logoutAll(userId:string,organizationId:string){await this.sessions.update({userId,organizationId,revokedAt:IsNull()},{revokedAt:new Date()});return {loggedOut:true};}
 async listSessions(userId:string,organizationId:string,q:SessionQueryDto){const order=toOrder(q.sortBy,q.sortDirection,['createdAt','updatedAt','expiresAt','revokedAt']as const,'createdAt');const[rows,total]=await this.sessions.findAndCount({where:{userId,organizationId},order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(rows.map(({refreshTokenHash,...safe})=>safe),total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 async revokeSession(userId:string,organizationId:string,id:string){const row=await this.sessions.findOneBy({id,userId,organizationId});if(!row)throw new DomainError('Session was not found','SESSION_NOT_FOUND',404);row.revokedAt=new Date();await this.sessions.save(row);return{revoked:true}}
 async me(userId:string,organizationId:string){const user=await this.users.findOneBy({id:userId,organizationId,isActive:true});if(!user)throw new UnauthorizedException();const {passwordHash,...safe}=user;return safe;}
 private async issueTokens(user:UserEntity,existing?:AuthSessionEntity){const session=existing??await this.sessions.save(this.sessions.create({userId:user.id,organizationId:user.organizationId,refreshTokenHash:'pending',expiresAt:new Date(Date.now()+7*86400000),rotation:0}));const common={sub:user.id,organizationId:user.organizationId,role:user.role,sessionId:session.id};const accessToken=this.jwt.sign(common,{secret:process.env.JWT_ACCESS_SECRET,expiresIn:'15m',issuer:'goverifeye-api',audience:'goverifeye-vendor-portal',algorithm:'HS256'});const refreshToken=this.jwt.sign({...common,rotation:session.rotation,purpose:'refresh'},{secret:process.env.JWT_REFRESH_SECRET,expiresIn:'7d',issuer:'goverifeye-api',audience:'goverifeye-refresh',algorithm:'HS256'});session.refreshTokenHash=this.hash(refreshToken);await this.sessions.save(session);return {accessToken,refreshToken,tokenType:'Bearer',expiresInSeconds:900};}
 private hash(value:string){return createHash('sha256').update(value).digest('hex');}
}
