import { Body, Controller, Get, HttpCode, Post, Req, Res, UnauthorizedException } from '@nestjs/common';
import type { Request, Response } from 'express';
import { ApiBadRequestResponse, ApiBody, ApiCreatedResponse, ApiExtraModels, ApiOkResponse, ApiOperation, ApiTags, getSchemaPath } from '@nestjs/swagger';
import { AuthService } from './auth.service'; import { ActionResponseDto, CurrentUserResponseDto, ForgotPasswordDto, ForgotPasswordResponseDto, LoginDto, OtpChallengeResponseDto, OtpVerifiedResponseDto, RefreshDto, RegisterDto, RequestOtpDto, ResetPasswordDto, ResetPasswordResponseDto, SessionQueryDto, SessionResponseDto, TokenResponseDto, VerifyOtpDto } from './dto/auth.dto'; import { CurrentUser, RequestContext } from '../common/request-context'; import { Delete,Param,Query } from '@nestjs/common';
import { Public } from './public.decorator';
import { Throttle } from '@nestjs/throttler';
import { ApiProtectedEndpoint, ApiPublicEndpoint, PageMetaDto } from '../common/swagger.dto';
@ApiTags('auth') @ApiExtraModels(SessionResponseDto,PageMetaDto) @Controller('auth') export class AuthController {
  constructor(private readonly auth: AuthService) {}
  @Public() @ApiPublicEndpoint() @ApiOperation({summary:'Request an email verification code',description:'Sends a six-digit OTP to the supplied email address. Use the returned challenge ID for tracking; the code is delivered through email.'}) @ApiBody({type:RequestOtpDto,examples:{request:{summary:'Request an OTP',value:{email:'tester@example.com'}}}}) @ApiCreatedResponse({type:OtpChallengeResponseDto}) @Throttle({default:{limit:5,ttl:60000}}) @Post('otp/request') request(@Body() dto: RequestOtpDto) { return this.auth.requestOtp(dto.email); }
  @Public() @ApiPublicEndpoint() @ApiOperation({summary:'Verify an email verification code',description:'Submit the opaque challenge ID returned by the OTP request endpoint and the six-digit code received by email.'}) @ApiBody({type:VerifyOtpDto,examples:{verify:{summary:'Verify an OTP',value:{challengeId:'f17fdb48-05ec-44bf-b882-d480c90e0c91',code:'123456'}}}}) @ApiOkResponse({type:OtpVerifiedResponseDto}) @Throttle({default:{limit:10,ttl:60000}}) @Post('otp/verify') @HttpCode(200) verify(@Body() dto: VerifyOtpDto) { return this.auth.verifyOtp(dto.challengeId, dto.code); }
  @Public() @ApiPublicEndpoint() @ApiOperation({summary:'Register an account after email verification'}) @ApiCreatedResponse({type:TokenResponseDto}) @Post('register') register(@Body() dto: RegisterDto) { return this.auth.register(dto.registrationToken, dto.password); }
  @Public() @ApiPublicEndpoint() @ApiOperation({summary:'Sign in with email and password'}) @ApiOkResponse({type:TokenResponseDto}) @Throttle({default:{limit:10,ttl:60000}}) @Post('login') @HttpCode(200) async login(@Body() dto: LoginDto,@Res({passthrough:true})response:Response) { const result=await this.auth.login(dto.email,dto.password,dto.rememberMe);this.refreshCookie(response,result.refreshToken,dto.rememberMe);return result; }
  @Public() @ApiPublicEndpoint() @ApiOperation({summary:'Request a password reset code',description:'Always returns the same response to prevent account discovery. If an active account exists, a six-digit, single-use reset code is emailed.'}) @ApiOkResponse({type:ForgotPasswordResponseDto}) @Throttle({default:{limit:5,ttl:60000}}) @Post('password/forgot') @HttpCode(200) forgotPassword(@Body()dto:ForgotPasswordDto){return this.auth.forgotPassword(dto.email)}
  @Public() @ApiPublicEndpoint() @ApiOperation({summary:'Reset a forgotten password with an OTP',description:'Validates and consumes the six-digit code, changes the password, and revokes every existing session.'}) @ApiOkResponse({type:ResetPasswordResponseDto}) @ApiBadRequestResponse({description:'The code is invalid/expired, the password fails validation, or the password matches the current password.',schema:{examples:{invalidCode:{value:{status:400,code:'PASSWORD_RESET_INVALID',title:'The password reset code is invalid or has expired'}},passwordReuse:{value:{status:400,code:'PASSWORD_REUSE_NOT_ALLOWED',title:'Choose a password different from your current password'}}}}}) @Throttle({default:{limit:10,ttl:60000}}) @Post('password/reset') @HttpCode(200) resetPassword(@Body()dto:ResetPasswordDto){return this.auth.resetPassword(dto.email,dto.code,dto.password)}
  @Public() @ApiPublicEndpoint() @ApiOperation({summary:'Rotate an access and refresh token pair'}) @ApiOkResponse({type:TokenResponseDto}) @Post('refresh') @HttpCode(200) async refresh(@Body()dto:RefreshDto,@Req()request:Request,@Res({passthrough:true})response:Response){const token=dto.refreshToken??this.cookie(request,'goverifeye_refresh');if(!token)throw new UnauthorizedException('Refresh token is required');const result=await this.auth.refresh(token);this.refreshCookie(response,result.refreshToken,result.rememberMe);return result}
  @ApiProtectedEndpoint() @ApiOperation({summary:'Sign out the current session'}) @ApiOkResponse({type:ActionResponseDto}) @Post('logout') @HttpCode(200) async logout(@CurrentUser()u:RequestContext,@Res({passthrough:true})response:Response){const result=await this.auth.logout(u.userId,u.organizationId,u.sessionId);response.clearCookie('goverifeye_refresh',{path:'/api/v1/auth'});return result}
  @ApiProtectedEndpoint() @ApiOperation({summary:'Sign out all sessions'}) @ApiOkResponse({type:ActionResponseDto}) @Post('logout-all') @HttpCode(200) logoutAll(@CurrentUser()u:RequestContext){return this.auth.logoutAll(u.userId,u.organizationId)}
  @ApiProtectedEndpoint() @ApiOperation({summary:'Get the authenticated user'}) @ApiOkResponse({type:CurrentUserResponseDto}) @Get('me') me(@CurrentUser()u:RequestContext){return this.auth.me(u.userId,u.organizationId)}
  @ApiProtectedEndpoint() @ApiOperation({summary:'List the authenticated user sessions'}) @ApiOkResponse({schema:{type:'object',properties:{data:{type:'array',items:{$ref:getSchemaPath(SessionResponseDto)}},meta:{$ref:getSchemaPath(PageMetaDto)}}}}) @Get('sessions') sessions(@CurrentUser()u:RequestContext,@Query()q:SessionQueryDto){return this.auth.listSessions(u.userId,u.organizationId,q)}
  @ApiProtectedEndpoint() @ApiOperation({summary:'Revoke a session'}) @ApiOkResponse({type:ActionResponseDto}) @Delete('sessions/:id') revoke(@CurrentUser()u:RequestContext,@Param('id')id:string){return this.auth.revokeSession(u.userId,u.organizationId,id)}
  private cookie(request:Request,name:string){const entry=request.headers.cookie?.split(';').map(value=>value.trim()).find(value=>value.startsWith(`${name}=`));return entry?decodeURIComponent(entry.slice(name.length+1)):undefined}
  private refreshCookie(response:Response,token:string,rememberMe=false){response.cookie('goverifeye_refresh',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:process.env.NODE_ENV==='production'?'none':'lax',path:'/api/v1/auth',...(rememberMe?{maxAge:30*86400000}:{})})}
}
