import { ConflictException, ForbiddenException, Inject, Injectable, Logger, UnauthorizedException } from '@nestjs/common'; import { ConfigType } from '@nestjs/config'; import { JwtService } from '@nestjs/jwt'; import { InjectRepository } from '@nestjs/typeorm'; import * as argon2 from 'argon2'; import { createHash, randomInt, randomUUID } from 'crypto'; import { DataSource, IsNull, Repository } from 'typeorm';
import appConfig from '../config/app.config'; import { AuthSessionEntity, OtpEntity, PasswordResetChallengeEntity, UserEntity } from './auth.entity'; import { SessionQueryDto } from './dto/auth.dto'; import { pageOf } from '../common/api-response'; import { toOrder } from '../common/page-query.dto'; import { DomainError } from '../common/domain-error';
import { ReliabilityService } from '../operations/reliability.service';
import { passwordResetCodeEmail, verificationCodeEmail } from '../operations/email-templates';
import { AuditLogEntity } from '../operations/operations.entity';
import { GovernanceService } from '../governance/governance.service';
import { EmailTemplateService } from '../operations/email-template.service';
interface RegistrationClaims {sub:string;email:string;purpose:'registration';challengeId:string}
interface RefreshClaims {sub:string;organizationId:string;role:string;sessionId:string;rotation:number;purpose:'refresh';rememberMe?:boolean}
@Injectable() export class AuthService {
 private readonly logger=new Logger(AuthService.name);
 constructor(@Inject(appConfig.KEY)private readonly options:ConfigType<typeof appConfig>,private readonly jwt:JwtService,@InjectRepository(UserEntity)private readonly users:Repository<UserEntity>,@InjectRepository(OtpEntity)private readonly otps:Repository<OtpEntity>,@InjectRepository(AuthSessionEntity)private readonly sessions:Repository<AuthSessionEntity>,private readonly db:DataSource,private readonly reliability:ReliabilityService,private readonly governance:GovernanceService,private readonly emailTemplates:EmailTemplateService){}
 async requestOtp(email:string){const normalized=email.trim().toLowerCase(),message='If this email is eligible for registration, a verification code will be sent.',existing=await this.users.existsBy({email:normalized});if(existing){this.logger.log(`Registration OTP suppressed reason=account_exists emailRef=${this.hash(normalized).slice(0,12)}`);throw new DomainError('Email already exists','EMAIL_ALREADY_EXISTS',409);}const code=randomInt(0,1_000_000).toString().padStart(6,'0'),expiresInMinutes=Math.ceil(this.options.otp.ttlSeconds/60);const row=await this.db.transaction(async manager=>{const saved=await manager.save(OtpEntity,manager.create(OtpEntity,{email:normalized,hash:await argon2.hash(code,{type:argon2.argon2id}),expiresAt:new Date(Date.now()+this.options.otp.ttlSeconds*1000)}));const emailContent=await this.emailTemplates.render(manager,'auth.registration_otp',{code,expiresInMinutes},()=>verificationCodeEmail(code,expiresInMinutes));await this.reliability.enqueue(manager,'email.send','otp',saved.id,{to:normalized,...emailContent});return saved});return {challengeId:row.id,expiresInSeconds:this.options.otp.ttlSeconds,message,...(process.env.NODE_ENV==='test'?{code}:{})};}
 async verifyOtp(challengeId:string,code:string){const record=await this.otps.findOne({where:{id:challengeId,consumed:false}});if(!record||record.expiresAt.getTime()<Date.now()||record.attempts>=this.options.otp.maxAttempts)throw new UnauthorizedException('Invalid or expired OTP');record.attempts+=1;if(!await argon2.verify(record.hash,code)){await this.otps.save(record);throw new UnauthorizedException('Invalid or expired OTP');}record.consumed=true;await this.otps.save(record);const key=record.email.trim().toLowerCase();const registrationToken=this.jwt.sign({sub:key,email:key,purpose:'registration',challengeId:record.id},{secret:process.env.JWT_ACCESS_SECRET,expiresIn:'10m',issuer:'goverifeye-api',audience:'goverifeye-registration'});return {verified:true,registrationToken,expiresInSeconds:600};}
 async register(registrationToken:string,password:string){let claims:RegistrationClaims;try{claims=await this.jwt.verifyAsync<RegistrationClaims>(registrationToken,{secret:process.env.JWT_ACCESS_SECRET,issuer:'goverifeye-api',audience:'goverifeye-registration'});}catch{throw new UnauthorizedException('Invalid or expired registration proof');}if(claims.purpose!=='registration')throw new UnauthorizedException('Invalid registration proof');if(await this.users.existsBy({email:claims.email}))throw new ConflictException('An account already exists for this email');const organizationId=randomUUID();const user=await this.users.save(this.users.create({email:claims.email,organizationId,passwordHash:await argon2.hash(password,{type:argon2.argon2id}),role:'admin',isActive:false}));return this.issueTokens(user);}
 async login(email:string,password:string,rememberMe=false){const normalized=email.trim().toLowerCase(),emailRef=this.hash(normalized).slice(0,12),user=await this.users.findOneBy({email:normalized});if(!user){this.logger.warn(`Login rejected reason=user_not_found emailRef=${emailRef}`);throw new UnauthorizedException('Invalid credentials');}if(!user.isActive&&!await this.isPendingVendorAdministrator(user)){this.logger.warn(`Login rejected reason=account_inactive userId=${user.id} organizationId=${user.organizationId} emailRef=${emailRef}`);throw new ForbiddenException('Your account is inactive. Contact your organization administrator or support.');}if(!await argon2.verify(user.passwordHash,password)){this.logger.warn(`Login rejected reason=password_mismatch userId=${user.id} organizationId=${user.organizationId} emailRef=${emailRef}`);throw new UnauthorizedException('Invalid credentials');}const challenge=await this.governance.beginLoginMfa(user,rememberMe);if(challenge)return challenge;this.logger.log(`Login successful userId=${user.id} organizationId=${user.organizationId} remembered=${rememberMe}`);return this.issueTokens(user,undefined,rememberMe);}
 async verifyLoginMfa(challengeId:string,code:string){const proof=await this.governance.completeLoginMfa(challengeId,code);const user=await this.users.findOneBy({id:proof.userId,organizationId:proof.organizationId,isActive:true});if(!user)throw new UnauthorizedException('Account is unavailable');return this.issueTokens(user,undefined,proof.rememberMe);}
 async forgotPassword(email:string){const normalized=email.trim().toLowerCase(),ttl=Math.max(5,Number(process.env.PASSWORD_RESET_TTL_MINUTES??10)),user=await this.users.findOneBy({email:normalized,isActive:true});if(user){const code=randomInt(0,1_000_000).toString().padStart(6,'0');await this.db.transaction(async manager=>{await manager.createQueryBuilder().update(PasswordResetChallengeEntity).set({consumed:true}).where('userId = :userId AND consumed = :consumed',{userId:user.id,consumed:false}).execute();const row=await manager.save(PasswordResetChallengeEntity,manager.create(PasswordResetChallengeEntity,{userId:user.id,email:normalized,codeHash:await argon2.hash(code,{type:argon2.argon2id}),expiresAt:new Date(Date.now()+ttl*60000)}));const variables={firstName:user.firstName,code,expiresInMinutes:ttl};const emailContent=await this.emailTemplates.render(manager,'auth.password_reset',variables,()=>passwordResetCodeEmail(variables));await this.reliability.enqueue(manager,'email.send','password-reset',row.id,{to:user.email,...emailContent})});}return{message:'If an account exists for that email, a password reset code has been sent.',expiresInSeconds:ttl*60};}
 async resetPassword(email:string,code:string,password:string){const normalized=email.trim().toLowerCase(),maxAttempts=Math.max(1,Number(process.env.PASSWORD_RESET_MAX_ATTEMPTS??5));const result=await this.db.transaction(async manager=>{const reset=await manager.findOne(PasswordResetChallengeEntity,{where:{email:normalized,consumed:false},order:{createdAt:'DESC'},lock:{mode:'pessimistic_write'}});if(!reset||reset.expiresAt.getTime()<=Date.now()||reset.attempts>=maxAttempts)return{error:'invalid' as const};reset.attempts+=1;if(!await argon2.verify(reset.codeHash,code)){await manager.save(PasswordResetChallengeEntity,reset);return{error:'invalid' as const};}const user=await manager.findOneBy(UserEntity,{id:reset.userId,email:normalized,isActive:true});if(!user)return{error:'invalid' as const};if(await argon2.verify(user.passwordHash,password))return{error:'reuse' as const};reset.consumed=true;await manager.save(PasswordResetChallengeEntity,reset);user.passwordHash=await argon2.hash(password,{type:argon2.argon2id});user.mustChangePassword=false;await manager.save(UserEntity,user);const now=new Date();await manager.createQueryBuilder().update(PasswordResetChallengeEntity).set({consumed:true}).where('userId = :userId AND consumed = :consumed',{userId:user.id,consumed:false}).execute();await manager.createQueryBuilder().update(AuthSessionEntity).set({revokedAt:now}).where('userId = :userId AND revokedAt IS NULL',{userId:user.id}).execute();await manager.save(AuditLogEntity,manager.create(AuditLogEntity,{organizationId:user.organizationId,actorId:user.id,action:'password.reset',resourceType:'user',resourceId:user.id,status:'success'}));return{passwordReset:true as const};});if('error'in result){if(result.error==='reuse')throw new DomainError('Choose a password different from your current password','PASSWORD_REUSE_NOT_ALLOWED',400);throw new DomainError('The password reset code is invalid or has expired','PASSWORD_RESET_INVALID',400);}return result;}
 async refresh(token:string){let claims:RefreshClaims;try{claims=await this.jwt.verifyAsync<RefreshClaims>(token,{secret:process.env.JWT_REFRESH_SECRET,issuer:'goverifeye-api',audience:'goverifeye-refresh'});}catch{throw new UnauthorizedException('Invalid refresh token');}const session=await this.sessions.findOneBy({id:claims.sessionId,userId:claims.sub,revokedAt:IsNull()});if(!session||session.expiresAt.getTime()<Date.now()||session.rotation!==claims.rotation||session.refreshTokenHash!==this.hash(token)){if(session){session.revokedAt=new Date();await this.sessions.save(session);}throw new UnauthorizedException('Refresh token replay or expiry detected');}const user=await this.users.findOneBy({id:claims.sub,organizationId:claims.organizationId});if(!user||(!user.isActive&&!await this.isPendingVendorAdministrator(user)))throw new UnauthorizedException('Account is unavailable');session.rotation+=1;return this.issueTokens(user,session,Boolean(claims.rememberMe));}
 async logout(userId:string,organizationId:string,sessionId:string){await this.sessions.update({id:sessionId,userId,organizationId,revokedAt:IsNull()},{revokedAt:new Date()});return {loggedOut:true};}
 async logoutAll(userId:string,organizationId:string){await this.sessions.update({userId,organizationId,revokedAt:IsNull()},{revokedAt:new Date()});return {loggedOut:true};}
 async listSessions(userId:string,organizationId:string,q:SessionQueryDto){const order=toOrder(q.sortBy,q.sortDirection,['createdAt','updatedAt','expiresAt','revokedAt']as const,'createdAt');const[rows,total]=await this.sessions.findAndCount({where:{userId,organizationId},order,skip:(q.page-1)*q.pageSize,take:q.pageSize});return pageOf(rows.map(({refreshTokenHash,...safe})=>safe),total,q.page,q.pageSize,q.sortBy,q.sortDirection)}
 async revokeSession(userId:string,organizationId:string,id:string){const row=await this.sessions.findOneBy({id,userId,organizationId});if(!row)throw new DomainError('Session was not found','SESSION_NOT_FOUND',404);row.revokedAt=new Date();await this.sessions.save(row);return{revoked:true}}
 async me(userId:string,organizationId:string){const user=await this.users.findOneBy({id:userId,organizationId});if(!user)throw new UnauthorizedException();const {passwordHash,...safe}=user;return safe;}
 private async issueTokens(user:UserEntity,existing?:AuthSessionEntity,rememberMe=false){const refreshDays=rememberMe?30:1;const session=existing??await this.sessions.save(this.sessions.create({userId:user.id,organizationId:user.organizationId,refreshTokenHash:'pending',expiresAt:new Date(Date.now()+refreshDays*86400000),rotation:0}));const common={sub:user.id,organizationId:user.organizationId,role:user.role,sessionId:session.id};const accessToken=this.jwt.sign(common,{secret:process.env.JWT_ACCESS_SECRET,expiresIn:'15m',issuer:'goverifeye-api',audience:'goverifeye-vendor-portal',algorithm:'HS256'});const refreshToken=this.jwt.sign({...common,rotation:session.rotation,purpose:'refresh',rememberMe},{secret:process.env.JWT_REFRESH_SECRET,expiresIn:`${refreshDays}d`,issuer:'goverifeye-api',audience:'goverifeye-refresh',algorithm:'HS256'});session.refreshTokenHash=this.hash(refreshToken);session.expiresAt=new Date(Date.now()+refreshDays*86400000);await this.sessions.save(session);return {accessToken,refreshToken,tokenType:'Bearer',expiresInSeconds:900,rememberMe,role:user.role,mustChangePassword:user.mustChangePassword,user:{id:user.id,email:user.email,firstName:user.firstName,lastName:user.lastName,organizationId:user.organizationId,role:user.role}};}
 private async isPendingVendorAdministrator(user:UserEntity){if(user.role!=='admin')return false;const row=await this.db.getRepository('organizations').createQueryBuilder('organization').select('organization.status','status').where('organization.id = :id',{id:user.organizationId}).getRawOne<{status?:string}>();return !row||['draft','submitted','changes_requested','rejected'].includes(String(row.status));}
 private hash(value:string){return createHash('sha256').update(value).digest('hex');}
}
